Fix `composer require` completion
When no development dependencies are installed, the completion would crash with:

    KeyError: 'require-dev'

(cherry picked from commit 9e223577aa95ea56b0907035bb50bbba5ae47d24)