Add an -A/--strict-argument-names option to function
The new -A/--strict-argument-names option behave like the existing
-a/--argument-names option to function, but with the following
differences:
  - If none of the argument names contains a ... suffix, it will be
  an error to call the function with a different number of arguments
  compared to the number of argument names.
  - If one of the argument names does contain a ... suffix, it will
  be an error to call it with less arguments, than non-... argument
  names.
  - it cannot be used together with -a/--argument-names (e.g.
  function f -A x -A y, and function f -a x -a y are allowed, but
  function f -A x -a y is not.)
  - It can be used without any argument argument names
  (e.g. function f -A), indicating that the function takes no arguments.

An error is produced as follows:
    - An error message of the following form is printed to stderr:
error: <name>: function requires exactly <n> arguments, but <m> where supplied
    - The function is not called
    - A status code of 2 is returned (similarly to other builtins
    when you provide them with an incorrect number/format of arguments)

Note that the error message is printed *before* the function is called,
so any redirections on the function call statement are not applied,
this is a bug that should be fixed.

This new feature fixes #11728.